services:
  db:
    image: postgres:17-alpine
    container_name: my_postgres_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - database_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bookstore_network


  redis:
    image: redis:7-alpine
    container_name: bookstore-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bookstore_network


  my-api:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    container_name: my-api-container
    environment:
      - DB_URL=${POSTGRES_URL}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PWD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - APP_FRONTEND_URL=${FRONTEND_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    networks:
      - bookstore_network
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
volumes:
  database_postgres:

networks:
  bookstore_network:


