CREATE TABLE BS_USER
(
    name    VARCHAR(100) NOT NULL,
    age     INTEGER      NOT NULL CHECK (age >= 0 AND age <= 120),
    email   VARCHAR(200) NOT NULL,
    address VARCHAR(300) NOT NULL
);

--TODO: CREATE A COMPLETE DATABASE FOR PROJECT WITH MORE TABLES AND INSERTS
