spring.application.name=bookstore

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


langchain4j.google-ai-gemini.chat-model.api-key=${GEMINI_API_KEY}
langchain4j.google-ai-gemini.chat-model.model-name=gemini-3-flash-preview
langchain4j.google-ai-gemini.chat-model.log-requests=true
langchain4j.google-ai-gemini.chat-model.log-responses=true


langchain4j.web-search-engine.tavily.api-key=${TAVILY_API_KEY}

logging.level.dev.langchain4j=DEBUG

logging.level.dev.langchain4j.web.search.tavily=DEBUG

logging.level.dev.langchain4j.model.googleai=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never